In [7]:
import pandas as pd

ids = pd.read_csv("./data/ids.csv")
tweets = pd.read_csv("./data/trump_tweets.csv")
tweets

,created_at,id,author_id,in_reply_to_user_id,text
0,2016-01-01T00:03:29.000Z,682713720368140290,724599002,NaN,actually the biggest loser in
1,2016-01-01T00:22:51.000Z,682718591821721600,395484842,25073877.0,is their some point to s life
2,2016-01-01T00:23:39.000Z,682718793785815040,113457921,18916432.0,u sold out in looking forward to
3,2016-01-01T00:34:18.000Z,682721474566696960,51623437,NaN,get the picture happy new years
4,2016-01-01T00:39:18.000Z,682722734124711937,269651436,NaN,chicago for new years wouldn t be complete wit...
...,...,...,...,...,...
119263,2016-12-30T23:17:26.000Z,814973700923682820,237509961,NaN,tweet f ks putin says can t wait till he gets ...
119264,2016-12-30T23:23:38.000Z,814975259912839168,237509961,NaN,finds banana splits tribute band to headline i...
119265,2016-12-30T23:54:53.000Z,814983125411344384,3092209045,NaN,they are followers without followers evil cann...
119266,2016-12-30T23:57:19.000Z,814983738518110208,16362541,759251.0,is now selling a book about lmao at this crazi...
119267,2016-12-30T23:59:57.000Z,814984401746620416,494509710,NaN,do you need more signs that trump is russia s

In [9]:
tweets = tweets[tweets.id.isin(ids.id)]

In [10]:
tweets

Empty DataFrame
Columns: [created_at, id, author_id, in_reply_to_user_id, text]
Index: []